name: build adocs

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    # 世の中のサンプルは殆ど master になったままになってるので注意
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "asciidoctor_job"
  asciidoctor_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build AsciiDoctor
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2
      # Output command using asciidoctor-action
      - name: Build AsciiDoc step
        id: documents
        uses: Analog-inc/asciidoctor-action@master
        with:
          # -o オプションで index.html に出力
          shellcommand: "asciidoctor index.adoc  -o index.html"

      # Deploy
      # この action の使い方: https://github.com/peaceiris/actions-gh-pages
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # .adoc ファイルは出力しない。.html と images だけが、gh-pages ブランチに出力される
          exclude_assets: ".adoc"
          publish_branch: gh-pages
          # ブランチに Directory が事前に無いと何も出力されない
          publish_dir: ./
